CREATE TABLE IF NOT EXISTS proxy
(
    id          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    proxy_type  INTEGER NOT NULL DEFAULT 0,
    config      TEXT    NOT NULL DEFAULT '',
    create_time TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP        DEFAULT CURRENT_TIMESTAMP
)